export const SDK_VALIDATION_ERROR_CODES = {
  INVALID_ROOT: 'SDK_INVALID_ROOT',
  INVALID_COLLECTION: 'SDK_INVALID_COLLECTION',
  INVALID_GROUP_ORDER: 'SDK_INVALID_GROUP_ORDER',
  INVALID_GROUPS_MAP: 'SDK_INVALID_GROUPS_MAP',
  INVALID_PROMPTS_MAP: 'SDK_INVALID_PROMPTS_MAP',
  INVALID_GROUP: 'SDK_INVALID_GROUP',
  INVALID_PROMPT: 'SDK_INVALID_PROMPT',
  MISSING_GROUP_REFERENCE: 'SDK_MISSING_GROUP_REFERENCE',
  MISSING_PROMPT_REFERENCE: 'SDK_MISSING_PROMPT_REFERENCE',
  GROUP_ID_MISMATCH: 'SDK_GROUP_ID_MISMATCH',
  PROMPT_ID_MISMATCH: 'SDK_PROMPT_ID_MISMATCH',
  EMPTY_GROUP_NAME: 'SDK_EMPTY_GROUP_NAME',
  DUPLICATE_GROUP_NAME: 'SDK_DUPLICATE_GROUP_NAME',
  INVALID_HOST_ERROR: 'HOST_INVALID_ERROR',
} as const

export type SdkValidationErrorCode = (typeof SDK_VALIDATION_ERROR_CODES)[keyof typeof SDK_VALIDATION_ERROR_CODES]
